version: '2'
services:

  jdk-9:
    image: openjdk:9-jdk
    volumes:
      - ./tools:/tools
      - ./assignments:/assignments

  jdk-8:
    build: ./docker/jdk8
    volumes:
      - ./tools:/tools
      - ./assignments:/assignments
